### PR TITLE
run UI tests in multiple browsers

### PR DESCRIPTION
**Pull request by individual-it**
This took a little bit longer that I've expected.
The first problem, and that took me a while to figure out, was the fact that the setting of env. variables does not work as expected in travis when separating them by a semicolon. They were somehow not correctly set. Need to separate them by a space (according to travis documentation)

**What tests are run now:**

- Chrome 48 on Linux, the newest Chrome that Saucelabs supports on Linux

- latest Chrome on Windows 10 (currently 57)

- latest-1 Chrome on Windows 10 (currently 56)

- oldest available Chrome (26) on Windows 10, as oC [claims to run on Chrome 18+ ](https://doc.owncloud.com/server/10.0/admin_manual/installation/system_requirements.html#web-browser)

- Firefox 47 on Windows 10 
webdriver for current Firefox is actually not ready, so we need to test on 47.0. see https://github.com/SeleniumHQ/selenium/issues/3693 & https://stackoverflow.com/questions/38746148/behat-mink-force-selenium-driver-to-use-chrome-instead-of-firefox#38764599

- oldest available Firefox (14) on Windows 10, as oC [claims to run on FF 14+ ](https://doc.owncloud.com/server/10.0/admin_manual/installation/system_requirements.html#web-browser)

- IE 11 on Windows 7
IE has a problem with one test (some JS problem) Notice: Undefined index: top in ... /tests/ui/features/bootstrap/FilesContext.php line 70

@phil-davis please review

### CODE REVIEW

**Comment by phil-davis** [comment]
For Chrome 48 on Linux and Firefox 47 on Windows10, can we just say "latest"? And that will always get a later version as it becomes available?

Why do you go back all the way to Firefox 14? Can the infrastructure do Firefox 18?

I wonder what the support is (should be) for Microsoft Edge on Windows 10. It is not mentioned in https://doc.owncloud.org/server/9.1/admin_manual/installation/system_requirements.html

**Comment by individual-it** [comment]
> For Chrome 48 on Linux and Firefox 47 on Windows10, can we just say "latest"?

- latest Chrome would give us 57, but that is not available on  Linux and it seems to fall back to Windows then
- there is a newer FF that 47 on Win 10, but it does not work

> Why do you go back all the way to Firefox 14? Can the infrastructure do Firefox 18?

typo, oC claims to run on FF 14+

> I wonder what the support is (should be) for Microsoft Edge on Windows 10.

tried, bu seems not to run stable on Saucelabs

**Comment by phil-davis** [comment]
That is annoying about IE11 on Win7 not starting. It is supposed to be a supported combination https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/ 
And it is listed at https://saucelabs.com/platforms
But down the bottom of that page is the versions of Windows that are actually used, e.g.
"For Windows 7, we use Windows Server 2008 R2"
That should be fine, but it does not mention what service pack. SP1 is required to even allow IE11 to be installed. https://support.microsoft.com/en-us/help/2847882/prerequisite-updates-for-internet-explorer-11

They announced IE11 on Windows8.1 in 2013 https://saucelabs.com/blog/windows-81-and-ie-11-now-available-on-sauce-labs so maybe that combination would work???

**Comment by individual-it** [comment]
IE 11 is starting and runs fine, except of one test does fail because getting the position of an element fails JS `getBoundingClientRect()` throws an error. This is a known bug but I don't expect MS to fix it :-)
So I found a way to skip tests with tags, see my last commit

**Comment by phil-davis** [comment]
In https://travis-ci.org/individual-it/owncloud-core/jobs/229952594 it said Could not open connection: Sauce could not start your job. For more information on what happened, please visit https://saucelabs.com/jobs/f49dcafa5b1649c19e4453cfe7fb1466 which then has:

Your test errored. The Sauce VMs failed to start the browser or device. For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages

So that was just a "random" SauceLabs infrastructure thing???

**Comment by individual-it** [comment]
closing at it went into oC https://github.com/owncloud/core/pull/27838

**Pull request closed without merging**
