### PR TITLE
A ui rename folder feature

### PR DESCRIPTION
**Pull request by individual-it**
some more renaming files & folders tests

### CODE REVIEW

**Comment by individual-it** [comment]
@phil-davis haven't asked you for a review on this yet

**Comment by individual-it** [comment]
yes some more funny characters and renaming folders, what could be different than renaming files

**Comment by phil-davis** [comment]
Yes, that was tricky trying to rename a folder to match a file.

**Comment by individual-it** [comment]
it will be more interesting when we manage to make it run on different storage backends

**Comment by individual-it** [comment]
closing as it got moved over to oC https://github.com/owncloud/core/pull/27931

**Pull request closed without merging**
