### PR TITLE
rerun failed tests

### PR DESCRIPTION
**Pull request by individual-it**
rerun tests that did fail the first time

### CODE REVIEW

**Comment by individual-it** [comment]
it's only restart the failed features and uses the string as its reported e.g 
`/home/travis/build/[secure]/owncloud-core/tests/ui/features/other/federationSharing.feature:13`

it should also work if multiple scenarios fail. then they will be reported as failed separately and rerun the same way

**Comment by individual-it** [comment]
basically this is automating the doggy thing we keep on doing (restarting test runs) but only retests the failed ones

**Comment by phil-davis** [comment]
I guess it will just rerun them once. If they fail the 2nd time then it will give a real error exit.

**Comment by individual-it** [comment]
closing as the rerun does not help much

**Pull request closed without merging**
